apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-deployment
spec:
  selector:
    matchLabels:
      app: node-redis
  template:
    metadata:
      labels:
        app: node-redis
    spec:
      containers:
      - name: node-redis
        image: arthurescriou/node-redis:1.0.6
        resources:
          limits:
            cpu : "1"
            memory : 512Mi
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379" 
---
apiVersion: v1
kind: Service
metadata:
  name: node-redis-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: node-redis  
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-redis-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-redis-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

