apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
        resources: &id001
          limits:
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
      - env:
        - name: REDIS_ADDR
          value: redis://localhost:6379
        image: oliver006/redis_exporter
        name: redis-exporter
        ports:
        - containerPort: 9121
        resources: *id001
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-service
spec:
  ports:
  - port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-deployment
  targetCPUUtilizationPercentage: 50
