apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "HelloWorld"  # Mot de passe
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "false"
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
data:
  datasource.yaml: |-    
    apiVersion: 1
    datasources:
    - name: prometheus-service
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-service.default.svc.cluster.local:9090
      isDefault: true
      editable: true

