global:
  evaluation_interval: 15s
  scrape_interval: 15s
scrape_configs:
- job_name: redis
  static_configs:
  - targets:
    - redis-service:6379
- job_name: node-app
  static_configs:
  - targets:
    - node-redis-service:8080
- job_name: react-app
  static_configs:
  - targets:
    - redis-react-service:80
