
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
        - name: redis-exporter
          image: oliver006/redis_exporter
          ports:
            - containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: "redis://localhost:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 9121
      targetPort: 9121
  type: ClusterIP
